Repository Qowaiv/qowaiv-js, pull requests merged in 2025-02, with the labels that each got.

#20 Represent empty with null
  README.md
  specs/Guid.spec.ts
  specs/InternationalBankAccountNumber.spec.ts
  specs/PostalCode.spec.ts
  src/Guid.ts
  src/InternationalBankAccountNumber.ts
  src/PostalCode.ts
  src/Svo.ts
Labels: enhancement

#23 Add length properties
  specs/InternationalBankAccountNumber.spec.ts
  specs/PostalCode.spec.ts
  src/InternationalBankAccountNumber.ts
  src/PostalCode.ts
Labels: enhancement

#24 Use slice() instead of substring()
  specs/Guid.spec.ts
  specs/Svo.specs.ts
  src/Guid.ts
  src/InternationalBankAccountNumber.ts
  src/PostalCode.ts
  src/Svo.ts
Labels: enhancement

#22 Implement email address
  specs/EmailAddress.spec.ts
  src/EmailAddress.ts
  src/Svo.ts
  src/index.ts
Labels: enhancement

#28 Add documentation on EmailAddress
  README.md
Labels: documentation

#27 Getting started docs
  GETTING_STARTED.md
  devbox.json
Labels: documentation

#29 Handling unparsable
  README.md
  specs/EmailAddress.spec.ts
  specs/Guid.spec.ts
  specs/InternationalBankAccountNumber.spec.ts
  specs/PostalCode.spec.ts
  src/EmailAddress.ts
  src/Guid.ts
  src/InternationalBankAccountNumber.ts
  src/PostalCode.ts
Labels: enhancement

#30 Support comments in IP-based email addresses
  specs/EmailAddress.spec.ts
  src/EmailAddress.ts
Labels: bug
